apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: cert-manager
spec:
  dnsNames:
    - "*.rajsingh.info"
  secretName: wildcard-rajsingh-info-tls
  issuerRef:
    name: rajsingh-info-global-issuer
    kind: ClusterIssuer