---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
spec:
  values:
    controller:
      service:
        labels:
          expose: yes
        type: LoadBalancer
        loadBalancerIP: 10.69.69.1