apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    expose: yes
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
    - name: stat
      protocol: TCP
      port: 1024
      targetPort: stat
  selector:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/name: haproxy
  type: LoadBalancer
  loadBalancerIP: 10.69.69.1
