apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-rajsingh-info-tls
  namespace: media
  annotations:
    item.homer.rajsingh.info/Logo: https://prowlarr.rajsingh.info/Content/Images/logo.svg
    item.homer.rajsingh.info/Name: "Prowlarr"
    item.homer.rajsingh.info/Type: Prowlarr
    item.homer.rajsingh.info/Apikey: b077c69d2a6c476da8f8e77fa9970a80
    item.homer.rajsingh.info/Target: _blank
    cert-manager.io/cluster-issuer: rajsingh-info-global-issuer
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: haproxy
  rules:
  - host: prowlarr.rajsingh.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696
  tls:
  - secretName: prowlarr-rajsingh-info-tls
    hosts:
    - prowlarr.rajsingh.info