apiVersion: v1
kind: Service
metadata:
  namespace: external-name
  name: docker-svc
spec:
  externalName: docker.lan
  ports:
  - name: code
    port: 8680
    protocol: TCP
    targetPort: 8680
  type: ExternalName