apiVersion: v1
kind: Service
metadata:
  namespace: external-name
  name: portainer-svc
spec:
  externalName: portainer.lan
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  sessionAffinity: None
  type: ExternalName
