apiVersion: v1
kind: Service
metadata:
  namespace: external-name
  name: uptime-svc
spec:
  externalName: uptime.lan
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  sessionAffinity: None
  type: ExternalName
