---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-local
spec:
  interval: 2m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: external-dns
      version: x
      sourceRef:
        kind: HelmRepository
        name: external-dns
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: EXTERNAL_DNS_PIHOLE_PASSWORD 
    extraArgs:
      - --pihole-server=http://pihole-web.pihole.svc.cluster.local
    provider:
      name: pihole
      webhook:
        args:
          - --source=service
          - --source=ingress
          - --registry=noop
          - --policy=upsert-only
          - --provider=pihole
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-prod
spec:
  interval: 2m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: external-dns
      version: x
      sourceRef:
        kind: HelmRepository
        name: external-dns
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: EXTERNAL_DNS_PIHOLE_PASSWORD 
    extraArgs:
      - --pihole-server=https://pihole.rajsingh.info
    provider:
      name: pihole
      webhook:
        args:
          - --source=service
          - --source=ingress
          - --registry=noop
          - --policy=upsert-only
          - --provider=pihole
    dnsConfig:
      nameservers:
      - 10.96.10.96
      - 10.96.96.10
