---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-local
spec:
  interval: 2m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: external-dns
      version: x
      sourceRef:
        kind: HelmRepository
        name: external-dns
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: EXTERNAL_DNS_PIHOLE_PASSWORD 
    args:
      - --source=service
      - --source=ingress
      - --registry=noop
      - --policy=upsert-only
      - --provider=pihole
      - '--pihole-server=http://pihole-web'
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: external-dns
# spec:
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       app: external-dns
#   template:
#     metadata:
#       labels:
#         app: external-dns
#     spec:
#       serviceAccountName: external-dns
#       containers:
#       - name: external-dns
#         image: registry.k8s.io/external-dns/external-dns:v0.14.1
#         # If authentication is disabled and/or you didn't create
#         # a secret, you can remove this block.
#         envFrom:
#         - secretRef:
#             # Change this if you gave the secret a different name
#             name: pihole-password
#         args:
#         - --source=service
#         - --source=ingress
#         # Pihole only supports A/CNAME records so there is no mechanism to track ownership.
#         # You don't need to set this flag, but if you leave it unset, you will receive warning
#         # logs when ExternalDNS attempts to create TXT records.
#         - --registry=noop
#         # IMPORTANT: If you have records that you manage manually in Pi-hole, set
#         # the policy to upsert-only so they do not get deleted.
#         - --policy=upsert-only
#         - --provider=pihole
#         # Change this to the actual address of your Pi-hole web server
#         - --pihole-server=http://pihole-web.pihole.svc.cluster.local
#       securityContext:
#         fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
