---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 2m
  chart:
    spec:
      chart: pihole
      version: x
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    DNS1: 8.8.8.8
    DNS2: 1.1.1.1
    admin:
      existingSecret: "pihole-password"
      passwordKey: password
    dnsmasq:
      customDnsEntries:
        - address=/.stg.rajsingh.info/10.69.69.1
        - address=/.rajsingh.info/10.69.69.2
    
      # customCnameEntries:
      #   - cname=foo.nas,nas

    persistentVolumeClaim:
      enabled: true

    serviceWeb:
      type: ClusterIP
    
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
      - 1.1.1.1
      - 8.8.8.8
