version: '3.8'

services:
  elb:
    restart: always 
    image: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"
    volumes:
        - haproxy-config:/usr/local/etc/haproxy
    # networks:
    #   macvlan:
    #     ipv4_address: 10.69.4.2
volumes:
  haproxy-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas.lan,rw
      device: ":/mnt/tank/portainer/haproxy-prod"