version: '3.8'

services:
  elb:
    restart: always 
    image: haproxytech/haproxy-debian
    networks:
      local-net:
        ipv4_address: 10.69.4.1
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"
    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  local-net:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 10.69.200.0/16