version: '3.8'

services:
  elb:
    restart: always 
    image: haproxy-debian
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"
    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - macvlan
# volumes:
#   haproxy-config:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=truenas.lan,rw
#       device: ":/mnt/tank/portainer/haproxy"

      