apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-system
resources:
  - ./namespace.yaml
  - ./gateway.networking.k8s.io_gatewayclasses.yaml
  - ./gateway.networking.k8s.io_gateways.yaml
  - ./gateway.networking.k8s.io_httproutes.yaml
  - ./gateway.networking.k8s.io_referencegrants.yaml
  - ./gateway.networking.k8s.io_tlsroutes.yaml
