---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  values:
    nfs:
      server: truenas.lan
      path: /mnt/tank/k8s
    