---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway-helm
      version: v0.0.0-latest
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: