apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
spec:
  interval: 5m
  path: ./
  prune: true
  sourceRef:
    kind: OCIRegistry
    name: envoy-gateway
    namespace: flux-system
  wait: true
  timeout: 2m