apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-rajsingh-info-tls
  namespace: external-name
  annotations:
    cert-manager.io/cluster-issuer: rajsingh-info-global-issuer
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: haproxy
  rules:
    - host: pihole.stg.rajsingh.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole-svc
                port:
                  number: 80
  tls:
    - secretName: pihole-rajsingh-info-tls
      hosts:
        - pihole.stg.rajsingh.info
