apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - ../base
  - ./ingress.yaml
  - ./service.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease