---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: kube-system
spec:
  values:
    serviceDns:
      loadBalancerIP: 10.69.69.10
      labels:
        expose: yes
      type: LoadBalancer
    