---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: kube-system
spec:
  values:
    hostname: "rajsingh-${CLUSTER_ENV/./-}"
    serviceDns:
      externalTrafficPolicy: Cluster
      loadBalancerIP: "10.96.11.96"
      mixedService: true
      nodePort: ""
      port: 53
      type: LoadBalancer
    ingress:
      annotations: 
        cert-manager.io/cluster-issuer: rajsingh-info-global-issuer
        kubernetes.io/tls-acme: "true"
      enabled: true
      hosts:
      - pihole${INGRESS_SUFFIX}
      path: /
      tls:
      - secretName: pihole-rajsingh-info-tls
        hosts:
          - pihole${INGRESS_SUFFIX}