# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: infrastructure-gateway
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./k8s/infrastructure/gateway/stg
#   prune: true
#   wait: true
#   timeout: 5m0s