--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  dnsNames:
    - "*.stg.rajsingh.info"
  secretName: wildcard-stg-rajsingh-info-tls
  issuerRef:
    name: rajsingh-info-global-issuer
    kind: ClusterIssuer