apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: https-rajsingh-info
    protocol: HTTPS
    port: 443
    tls:
      certificateRefs:
      - name: wildcard-rajsingh-info-tls
    allowedRoutes:
      namespaces:
        from: All