apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: rajsingh-info
spec:
  gatewayClassName: envoy-proxy-rajsingh-info
  listeners:
  - name: https-rajsingh-info
    protocol: HTTPS
    port: 443
    tls:
      certificateRefs:
      - name: wildcard-rajsingh-info-tls
    allowedRoutes:
      namespaces:
        from: All