apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering-policy
spec: 
 nodeSelector:
   matchLabels:
     kubernetes.io/os: linux
 virtualRouters: 
 - localASN: 64514
   exportPodCIDR: true
   neighbors: 
    - peerAddress: '10.69.0.1/32'
      peerASN: 64513
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
    - peerAddress: '10.69.0.1/32'
      peerASN: 64513
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
        