---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    cluster:
      id: 3
      name: tooling
    k8sServiceHost: k8s-tooling.lan
    k8sServicePort: 6443
    operator:
      replicas: 1
    bgpControlPlane:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    ipv6:
      enabled: false
    k8s-require-ipv4-pod-cidr: true
    kubeProxyReplacement: strict
    ipam:
      mode: kubernetes
    tunnel: vxlan
    externalIPs:
      enabled: true
    hostPort:
      enabled: true
    hostServices:
      enabled: false