---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
spec:
  interval: 15m
  chart:
    spec:
      chart: haproxy-ingress
      version: x
      sourceRef:
        kind: HelmRepository
        name: haproxy
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller: 
      ingressClassResource:
        enabled: true
        default: true
      hostNetwork: true
