---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
spec:
  interval: 2m
  chart:
    spec:
      chart: haproxytech/kubernetes-ingress
      version: 1.34.1
      sourceRef:
        kind: HelmRepository
        name: haproxy
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # controller: 
    #   ingressClassResource:
    #     enabled: true
    #     default: true
    #   hostNetwork: true
