---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./argo.yaml
  - ./jetstack.yaml
  - ./cilium.yaml
  - ./haproxy.yaml
  - ./pihole.yaml
  - ./truecharts.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./prometheus-k8s.yaml