---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo
  namespace: argo
spec:
  interval: 2m
  chart:
    spec:
      chart: argo
      version: x
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    