---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 2m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: prometheus
      version: x
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: