apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi