apiVersion: v1
kind: Service
metadata:
  name: transmission-openvpn
spec:
  selector:
    app: transmission-openvpn
  ports:
  - name: http
    port: 8006
    protocol: TCP
    targetPort: 8006
  type: ClusterIP