---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: kube-system
spec:
  values:
    hostname: "rajsingh-prod"
    serviceDns:
      loadBalancerIP: "10.96.10.96"
      loadBalancerIPv6: ""
      mixedService: true
      nodePort: ""
      port: 53
      type: LoadBalancer