---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  path: ./k8s/infrastructure/nfs-subdir-external-provisioner/k8s-stg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m