apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
      - command:
        - cloudflared
        - tunnel
        - --metrics
        - 0.0.0.0:2000
        - run
        args:
        - --token 
        - $(token)
        image: cloudflare/cloudflared:latest
        name: cloudflared
        env:
        - name: token
          valueFrom:
            secretKeyRef:
              name: cloudflared
              key: TunnelSecret
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.5" 
            memory: "256Mi"  
          requests:
            cpu: "0.2"  
            memory: "128Mi"  
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.69.10.69
        - 10.69.69.10