apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/cilium
  - ./ippool.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease