apiVersion: v1
kind: Service
metadata:
  name: transmission-tv
spec:
  selector:
    app: transmission-tv
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  type: ClusterIP