apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../base
  - ./ippool.yaml
  - ./bgp.yaml
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease