---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    cluster:
      id: 2
      name: ${CLUSTER_ENV}
    k8sServiceHost: k8s-stg1.lan
    k8sServicePort: 6443
    bgpControlPlane:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          annotations: 
            cert-manager.io/cluster-issuer: rajsingh-info-global-issuer
            kubernetes.io/tls-acme: "true"
          className: "cilium"
          enabled: true
          hosts:
          - hubble${INGRESS_SUFFIX}
          labels: {}
          tls:
            - secretName: hubble-rajsingh-info-tls
              hosts:
                - hubble${INGRESS_SUFFIX}
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    ipv6:
      enabled: false
    k8s-require-ipv4-pod-cidr: true
    kubeProxyReplacement: strict
    ipam:
      mode: kubernetes
    tunnel: vxlan
    externalIPs:
      enabled: true
    hostPort:
      enabled: true
    hostServices:
      enabled: false
    envoyConfig:
      enabled: true
    loadBalancer:
      l7:
        backend: envoy
    ingressController:
      enabled: true
      loadbalancerMode: dedicated
      default: true
      enforceHttps: false
      # service:
      #   type: LoadBalancer
      #   loadBalancerIP: 10.96.11.1
    egressGateway:
      enabled: true
    bpf:
      masquerade: true