---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    bgp:
      enabled: false
    bpf:
      masquerade: true
    devices:
    - eth0
    enableIPv6Masquerade: false
    endpointRoutes:
      enabled: true
    externalIPs:
      enabled: true
    externalWorkloads:
      enabled: false
    extraConfig:
      enable-ipv6-ndp: "false"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv4MaskSize: 16
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    ipv4:
      enabled: true
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    ipv6:
      enabled: false
    k8s-require-ipv4-pod-cidr: true
    k8s-require-ipv6-pod-cidr: false
    k8sClientRateLimit:
      burst: 25
      qps: 10
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    l2announcements:
      enabled: true
      leaseDuration: 300s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 10s
    localRedirectPolicy: true
    routingMode: tunnel
    securityContext:
      privileged: true
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    tunnel: vxlan
    cluster:
      id: 2
      name: stg
    k8sServiceHost: 10.69.201.201
    operator:
      replicas: 1