apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: lscr.io/linuxserver/jackett:latest
        ports:
        - name: http
          containerPort: 9117
          protocol: TCP
        volumeMounts:
        - name: downloads-volume
          mountPath: /downloads
        - name: config-volume
          mountPath: /config
        env:
        - name: PUID
          value: "0"
        - name: GUID
          value: "0"
        - name: TZ
          value: America/Chicago
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: jackett-data
      - name: config-volume
        persistentVolumeClaim:
          claimName: jackett-config