apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/cert-manager
  prune: true
  wait: true

  dependsOn:
    - name: infrastructure-cilium