apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/nfs-subdir-external-provisioner/stg
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure-cilium