---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    cluster:
      id: 1
      name: prod
    k8sServiceHost: 10.69.200.0
    