---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rajsingh-info-global-issuer
spec:
  acme:
    email: rajsinghcpre@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: rajsinghcpre@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token